### ISSUE TITLE
Schedule tweets for all the demos!

### ISSUE THREAD

**Issue by acabunoc** [mozilla/leadership-training#30]
Hello hello!

Links to all the timestamped demos are in this post, along with project name and twitter handles for the project leads
https://medium.com/read-write-participate/demos-recap-e4f1d0de3dc1

I'd love to have tweets go out this week for all the projects that demo-ed on the @MozOpenLeaders account. Anyone interested in helping me schedule these all?

Much appreciated :)

**Comment by princiya** [comment]
Sure, let me know how to go about :) Happy to help here.

**Comment by yochannah** [comment]
I'd be happy to do some too - I could do CohortZilla's if you like?

**Comment by acabunoc** [comment]
Thanks all ❤️!

I'll send over the credentials to the three of you. I'll let you decide how to divvy it up! Just make sure they're spaced apart by a bit & scheduled around some peak times.

**Comment by rainsworth** [comment]
The #OpenSucculentProject🌵 tweets have all been scheduled for tonight and tomorrow. I used this format:

Catch the final demo for ___ by our Round 4 grad ___! #OpenSucculentProject🌵
📝: https://public.etherpad-mozilla.org/p/ol4-demos-b#lineNumber=378
🎥: https://air.mozilla.org/mozilla-open-leaders-round-4-final-demos-open-succulent-project/#@86m18s

**Comment by yochannah** [comment]
Nice job @rainsworth!

My bit's done too: #Cohortzilla🦎 tweets have been scheduled for the 13th and 14th! :)

**Comment by princiya** [comment]
Done done! #RebelFoxes🦊  for today, tomorrow and the day after :)

**Comment by acabunoc** [comment]
Thanks all! Hugely appreciated 🎉 

Closing this and watching the tweets go out!
